module.exports = [
    "Aasterinian",
    "Abbathor",
    "Adad",
    "Aegir",
    "Aengrist",
    "Aerdrie Faenya",
    "Afflux",
    "Afrodyta",
    "Agni",
    "Ahto",
    "Akadi",
    "Al'Akbar",
    "Alathrien Druanna",
    "Al-Ishtus",
    "Allitur",
    "Alobal Lorfiril",
    "Altua",
    "Aluvan",
    "Amaterasu",
    "Amaunator",
    "Angharradh",
    "Anhur",
    "Annam",
    "Anshar",
    "Anu",
    "Anubis",
    "Ao",
    "Aoskar",
    "Apollo",
    "Apopis",
    "Apshai",
    "Araleth Letheranil",
    "Arawai",
    "Arawn",
    "Ares",
    "Artemida",
    "Arvoreen",
    "Asmodeusz",
    "Astilabor",
    "Atena",
    "Atroa",
    "Aulasha",
    "Auppenser",
    "Aureon",
    "Aurifar",
    "Auril",
    "Avandra",
    "Aventernus",
    "Ayailla",
    "Azathoth",
    "Azor'alq",
    "Azul",
    "Azuth",
    "Baervan Włóczykij",
    "Bafomet",
    "Bahamut",
    "Bahgtru",
    "Balador",
    "Balder",
    "Beli-ili",
    "Balinor",
    "Bane",
    "Baravar Cienista Szata",
    "Bargrivyek",
    "Bastet",
    "Belenus",
    "Beltar",
    "Beory",
    "Berei",
    "Berna",
    "Berronar Czyste Srebro",
    "Bes",
    "Beshaba",
    "Beztwarzowy Bóg",
    "Bhaal",
    "Bleredd",
    "Blibdoolpoolp",
    "Boccob",
    "Bogowie Księżyca",
    "Bokrug",
    "Boldrei",
    "Brahman",
    "Bralm",
    "Branchala",
    "Brandobaris",
    "Breeka",
    "Brigit",
    "Bryhaspati",
    "Callarduran Gładkoręki",
    "Camazotz",
    "Caoimhin",
    "Cas",
    "Cegilune",
    "Celestian",
    "Cernunnos",
    "Chaav",
    "Chaniud",
    "Chaos (Dragonlance)",
    "Charmalaine",
    "Chaugnar Faugn",
    "Chauntea",
    "Chemosh",
    "Chislev",
    "Chitza-Atlan",
    "Chronepsis",
    "Chung Kuel",
    "Cierpliwy",
    "Cień (bóstwo)",
    "Clangeddin Srebrnobrody",
    "Corantillil",
    "Corellon Larethian",
    "Crysa-Thul",
    "Cthugha",
    "Cthulhu",
    "Cyndor",
    "Cyric",
    "Cyrrollalee",
    "Czerwona Rycerka",
    "Daern",
    "Dagda",
    "Dagon (przedwieczny)",
    "Dallah Thaun",
    "Dalt",
    "Damaran",
    "Damh",
    "Daoud",
    "Daragor",
    "Delleb",
    "Demeter",
    "Dendar",
    "Deneir",
    "Dennari",
    "Darahl Tivenar",
    "Diancastra",
    "Diancecht",
    "Diinkarazan",
    "Diirinka",
    "Dionizos",
    "Diophia",
    "Dol Arrah",
    "Dol Dorn",
    "Doresain",
    "Dracanish",
    "Droga Inspiracji",
    "Droga Światła",
    "Druaga",
    "Duchy Przeszłości",
    "Duerra z Podziemi",
    "Dugmaren Jasny Płaszcz",
    "Dumathoin",
    "Dunatis",
    "Durann",
    "Duthila",
    "Ea",
    "Eachthighern",
    "Eadro",
    "Eanius",
    "Ehlonna",
    "Eihort",
    "Eilistraee",
    "Eldath",
    "Elebrin Liothiel. Elishar",
    "Emmantiensien",
    "Enki",
    "Enlil",
    "Epona",
    "Erathis",
    "Ereb",
    "Ereshkigal",
    "Erevan Ilesere",
    "Erivatius",
    "Erythnul",
    "Eshebala",
    "Essylliss",
    "Estanna",
    "Ezra",
    "Faluzure",
    "Fenmarel Mestarine",
    "Ferrix",
    "Fharlanghn",
    "Fionnghuala",
    "Flandal Stalowoskóry",
    "Forin",
    "Forseti",
    "Fortubo",
    "Freja",
    "Frey",
    "Frigg",
    "Furia (bóstwo)",
    "Gadhelyn",
    "Gaerdal Żelaznoręki",
    "Gaknulak",
    "Galaedros",
    "Galtha",
    "Garagos",
    "Gargauth",
    "Garl Świetlistozłoty",
    "Garyx",
    "Geb",
    "Gelf Czarne Kowadło",
    "Gendwar Argrim",
    "Geshtai",
    "Ghaunadaur",
    "Gilean",
    "Gilgamesz",
    "Gilgeam",
    "Girru",
    "Glaaki",
    "Glautru",
    "Goibhniu",
    "Golgoroth",
    "Gond",
    "Gorellik",
    "Gorm Gulthyn",
    "Grankhul",
    "Grolantor",
    "Grumbar",
    "Gruumsh",
    "Gwaeron Wichura",
    "Gzemnid",
    "Haaashastaak",
    "Habbakuk",
    "Hachiman",
    "Hades",
    "Haela Jasny Topór",
    "Haelyn",
    "Hadżama",
    "Hakija",
    "Haku",
    "Halav",
    "Halmyr",
    "Halnass",
    "Hanali Celanil",
    "Hanish",
    "Hanseath",
    "Hanuman Przeklęty",
    "Haoma",
    "Hapi",
    "Hara",
    "Hastseltsi",
    "Hastur",
    "Hathor",
    "Haumea",
    "Haumia",
    "Hefajstos",
    "Hekate",
    "Hei",
    "Heimdall",
    "Heironeous",
    "Hel",
    "Helm",
    "Hera",
    "Hercon",
    "Herkules (Herakles)",
    "Hermes",
    "Hermod",
    "Hestia",
    "Heward",
    "Hextor",
    "Hi-iaka",
    "Hiatea",
    "Hiddukel",
    "Hiisi",
    "Hina",
    "Hishrak",
    "Hisk",
    "Hlal",
    "Hleid",
    "Hlyyaak",
    "Ho Masubi",
    "Hoar",
    "Hoenir",
    "Hongatar",
    "Horus",
    "Hotei",
    "Hrea",
    "Hred",
    "Hruggek",
    "Hrussiall'k",
    "Huhueteotl",
    "Huitzilopochtli (Huitzilopoohtli)",
    "Hurakon",
    "Hydra",
    "Hypnatia",
    "Iallanis",
    "Iborighu",
    "Ibrandul",
    "Idh-yaa",
    "Ilmatar",
    "Ilmater",
    "Ilneval",
    "Ilsensine",
    "Imhotep",
    "Inanna",
    "Incabulos",
    "Indra",
    "Io",
    "Ioun",
    "Istishia",
    "Istus",
    "Isztar",
    "Ithaqua",
    "Iuz",
    "Ixtilli",
    "Iyachtu Xvim",
    "Izyda",
    "Jama",
    "Jascar",
    "Jazirian",
    "Jergal",
    "Johydee",
    "Joramy",
    "Kaelthiere",
    "Kali",
    "Kanchelsis",
    "Karaan",
    "Karontor",
    "Karttikeja",
    "Katay",
    "Kavaki",
    "Ka’jik’zxi",
    "Kelanen",
    "Kelemvor",
    "Keoghtom",
    "Keptolo",
    "Khendovar",
    "Khostren",
    "Khurgorbaeyag",
    "Ki",
    "Kiaransalee",
    "Kikanuti",
    "Kil'lix",
    "Kiltzi",
    "Kiri-Jolith",
    "Kirith Sotheril",
    "Kithin",
    "Kol Korran",
    "Konkresh",
    "Kord",
    "Kossuth",
    "Krucza Królowa",
    "Królowa Powietrza i Ciemności",
    "Królowie Burzy",
    "Kr'tx",
    "Kuliak",
    "Kundo",
    "Kuraulyek",
    "Kurell",
    "Kuroth",
    "Kurtulmak",
    "Kyuss",
    "Labelas Enoreth",
    "Laduguer",
    "Lakszmi",
    "Laogzed",
    "Lastai",
    "Lathander",
    "Lei Kung",
    "Leira",
    "Lendor",
    "Lendys",
    "Lew Wodny",
    "Lunara",
    "Lirr",
    "Llerg",
    "Lliendil",
    "Lliira",
    "Loki",
    "Lolth",
    "Loviatar",
    "Lugh",
    "Lunitari",
    "Lurue",
    "Luthic",
    "Lydia",
    "Lyris",
    "Maanzecorian",
    "Maglubiyet",
    "Majere",
    "Mak Thuum Ngatha",
    "Malar",
    "Malyk",
    "Manannan mac Lir",
    "Manethak",
    "Marduk",
    "Marthammor Duin",
    "Maska",
    "Math Mathonwy",
    "Matka Wielorybów",
    "Mayaheine",
    "Melira Taralen",
    "Mellifleur",
    "Melora",
    "Memnor",
    "Meriadar",
    "Merikka",
    "Merrshaulk",
    "Meyanok",
    "Mictlantecuhtli",
    "Mielikki",
    "Milil",
    "Mina",
    "Mishakal",
    "Mistrz Łowu",
    "Mitra",
    "Moander",
    "Moradin",
    "Mordiggian",
    "Morgion",
    "Morrigan",
    "Mouqol",
    "Muamman Duathal",
    "Murlynd",
    "Mya",
    "Myhriss",
    "Myrkul",
    "Mythrien Sarath",
    "Mystra",
    "M'daess",
    "Naddusza",
    "Nadirech",
    "Naki-Uthai",
    "Nanna-Sin",
    "Naralis Anarol",
    "Nathair Sgiathach",
    "Nazarn",
    "Nebelun",
    "Neftyda",
    "Nergal",
    "Nerull",
    "Nessek",
    "Nike",
    "Nilthina",
    "Ninurta",
    "Nin-Hursag",
    "Njord",
    "Nobanion",
    "Nodens",
    "Nola",
    "Nomog-Geaya",
    "Norebo",
    "Nuada",
    "Nuitari",
    "Null",
    "Nut",
    "Nyarlathotep",
    "Nyogtha",
    "Obad-Hai",
    "Oberon",
    "Od",
    "Odyn",
    "Oghma",
    "Oghma (panteon celtycki)",
    "Olidammara",
    "Olladra",
    "Onatar",
    "Orkus",
    "Osprem",
    "Ozyrys",
    "Paladine",
    "Pan",
    "Pan Kotów",
    "Panzuriel",
    "Parrafaire",
    "Pelor",
    "Persana",
    "Phaant",
    "Phaulkon",
    "Phieran",
    "Pholtus",
    "Phyton",
    "Piscaethces",
    "Posejdon",
    "Poszukiwacz Wyvernspur",
    "Powstający Bóg",
    "Pożeracz (bóstwo eberrońskie)",
    "Primus",
    "Procan",
    "Psilofyr",
    "Ptah",
    "Puszan",
    "Pyremius",
    "P'kk",
    "Qebhsennuf",
    "Qotal",
    "Quetzalcoatl (Kulkulkan)",
    "Quorggg",
    "Quorlinn",
    "Ra",
    "Raei",
    "Ralishaz",
    "Rallaster",
    "Ramenos",
    "Ramman",
    "Rao",
    "Ratri",
    "Ravanna",
    "Raxivort",
    "Re-Horachty",
    "Rellavar Danuvien",
    "Remnis",
    "Reorx",
    "Rill Mądry Drozd",
    "Rillifane Rallathil",
    "Roknar",
    "Roykyn",
    "Rudd",
    "Rudra",
    "Sardior",
    "Sargonnas",
    "Sarula Iliene",
    "Sashelas z Głębin",
    "Savras",
    "Sawitri",
    "Scahrossar",
    "Segojan Herold Ziemi",
    "Sehanine Księżycowy Łuk",
    "Seker",
    "Sekolah",
    "Selûne",
    "Selvetarm",
    "Semuanya",
    "Set",
    "Shamash",
    "Shang-ti",
    "Shar",
    "Sharess",
    "Shargaas",
    "Sharindlar",
    "Shaundakul",
    "Sheela Peryroyl",
    "Shekinester",
    "Shevarash",
    "Sheyanna Lniana Nić",
    "Shiallia",
    "Shinare",
    "Shub-Niggurath",
    "Shudde M'ell",
    "Siamorphe",
    "Sif",
    "Sifraniska",
    "Silvanus",
    "Silvanus (panteon celtycki)",
    "Sin",
    "Sirrion",
    "Sixin",
    "Skadi",
    "Skerrit",
    "Skiggaret",
    "Skoraeus Kamienne Kości",
    "Smok Ziemi",
    "Sobek",
    "Soggelos",
    "Solanil",
    "Solinari",
    "Solonor Thelandira",
    "Soma",
    "Soorinek",
    "Sotillion",
    "Squelaiche",
    "Squerrik",
    "Srebrny Płomień",
    "Sroga Alia",
    "Sseth",
    "Ssharstrune",
    "Sss'thasine'ss",
    "Starsze Oko Żywiołów",
    "Strażnik Martwych Bogów",
    "Stronmaus",
    "Stróż",
    "Sulerain",
    "Sune",
    "Sung Chiang",
    "Surja",
    "Surma",
    "Surminare",
    "Surtur",
    "Syeret",
    "Syranita",
    "Syreth",
    "Syrul",
    "Sziwa",
    "Szu",
    "Szyderca",
        "Taiia",
    "Takhisis",
    "Talona",
    "Talos",
    "Tamara",
    "Tapann",
    "Tarmuid",
    "Tarsellis Meunniduin",
    "Task",
    "Tchazzar",
    "Tefnut",
    "Telchur",
    "Tem-Et-Nu",
    "Tempus",
    "Tenebrous",
    "Tephaneron",
    "Tethrin Veraldé",
    "Tezcatlipoca",
    "Thard Harr",
    "Tharizdun",
    "Tharmekhûl",
    "Thautam",
    "Theleya",
    "Thelmeth Unifikator",
    "Thoon",
    "Thor",
    "Thrig'ki",
    "Thrym",
    "Tiamat",
    "Tlazoteotl",
    "Toldoth",
    "Torm",
    "Torog",
    "Tot",
    "Trishina",
    "Trithereon",
    "Tsathoggua",
    "Tsolorandril",
    "Tuilviela Glithien",
    "Tulzscha",
    "Tuonetar",
    "Tuoni",
    "Twasztar",
    "Tyche",
    "Tymora",
    "Typhos",
    "Tyr",
    "Tyr (panteon asgardzki)",
    "Tytania",
    "T'zen'kil",
    "Ubtao",
    "Uhanam",
    "Uin",
    "Ukko",
    "Ulaa",
    "Ull",
    "Ulutiu",
    "Umberlee",
    "Untamo",
    "Urbanus",
    "Urdlen",
    "Urogalan",
    "Uszas",
    "Uthgar",
    "Utu",
    "Uvot",
    "Waju",
    "Walkirie",
    "Waruna",
    "Wastri",
    "Wathaku",
    "Waukeen",
    "Wee Jas",
    "Wenta",
    "Wędrowiec",
    "Wieczne Światło",
    "Wieczorna Chwała",
    "Wiekuisty Dwór",
    "Wielka Matka",
    "Wilczy Bóg",
    "Wisznu",
    "Wyst",
    "Władca Ostrzy",
    "Valarian",
    "Valkar",
    "Valkauna",
    "Valkur",
    "Vandria Gilmadrith",
    "Vanua",
    "Vaprak",
    "Vara",
    "Varae",
    "Vathris",
    "Vatun",
    "Vecna",
    "Velnius",
    "Velsharoon",
    "Ventila",
    "Verenestra",
    "Vergadain",
    "Vesperian",
    "Vhaeraun",
    "Vogan",
    "Xammux",
    "Xan Yae",
    "Xanag",
    "Xerbo",
    "Xann",
    "Y'golonac",
    "Yakushi-Nyorai",
    "Yalungur",
    "Yama-Uba",
    "Yan-Io",
    "Ye'Cind",
    "Yeathan",
    "Yemoja",
    "Yen-Wang-Yeh",
    "Yezud",
    "Yig",
    "Yog-Sothoth",
    "Yondalla",
    "Yurlunggur",
    "Yurtrus",
    "Zagyg",
    "Zaltec",
    "Zandilar",
    "Zargon",
    "Zarkon",
    "Zarus",
    "Zeboim",
    "Zehir",
    "Zeus",
    "Zhakta",
    "Zilchus",
    "Zinzerena",
    "Zirchev",
    "Zivilyn",
    "Zkracl",
    "Zodal",
    "Zorquan",
    "Zoser",
    "Zrunta Serce Góry",
    "Zuoken",
    "Z'zelth",
    "Święty Cuthbert"
]